use std::fmt::Write as _;
use std::{env, fs, path::Path};

fn main() {
    tauri_build::build();
    write_built_in_table();
}

/// The colour fields a theme may carry, all of which must be hex if they are
/// there at all. Kept in step with `Theme` in `theme.rs` and with `parseColor`
/// in `themes.ts`, which is the function that decides at runtime whether a
/// colour can be read.
const COLORS: &[&str] = &[
    "text",
    "background",
    "accent",
    "link",
    "selection_area",
    "selection_text",
];

/// Generate the `BUILT_IN` table from the directory rather than from a list
/// somebody has to remember to edit.
///
/// `include_str!` needs a path it can see at macro-expansion time, and Rust
/// cannot glob there — which is the whole reason the table was ever written
/// out by hand. A build script can, so the shipped set becomes what is in
/// `themes/`, and adding a theme is adding a file.
///
/// The one thing a directory cannot say is what order to list them in: that is
/// an editorial decision (the Hylo family first, then the rest), so each
/// shipped file carries an `order`. It is meaningless in a theme of your own —
/// those are listed after the built-ins and sorted by name — and the app never
/// writes it, so a copy made through the theme editor does not inherit one.
///
/// Everything here that can fail, fails the build. A shipped theme that will
/// not parse is dropped silently at runtime, and one with an unreadable colour
/// reaches the reader as a notice meant for themes they wrote themselves;
/// neither is a way to find out about a file that ships in the binary.
fn write_built_in_table() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("themes");
    println!("cargo:rerun-if-changed=themes");
    println!("cargo:rerun-if-changed=build.rs");

    let mut themes: Vec<(i64, String)> = Vec::new();
    for entry in fs::read_dir(&dir).expect("themes directory").flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let id = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("theme file name")
            .to_string();
        let source = fs::read_to_string(&path).unwrap_or_else(|e| panic!("themes/{id}.toml: {e}"));
        themes.push((check(&id, &source), id));
    }

    themes.sort();
    for pair in themes.windows(2) {
        assert!(
            pair[0].0 != pair[1].0,
            "themes/{}.toml and themes/{}.toml both claim order {}",
            pair[0].1,
            pair[1].1,
            pair[0].0,
        );
    }

    let mut out = String::from(
        "/// The themes that ship with HyloPDF, in the order they are listed in,\n\
         /// generated by `build.rs` from the contents of `themes/`.\n\
         pub const BUILT_IN: &[(&str, &str)] = &[\n",
    );
    for (_, id) in &themes {
        let _ = writeln!(
            out,
            "    ({id:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/themes/{id}.toml\"))),"
        );
    }
    out.push_str("];\n");

    let target = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("built_in.rs");
    fs::write(&target, out).expect("write the built-in theme table");
}

/// Check one shipped theme and return the order it asked for.
fn check(id: &str, source: &str) -> i64 {
    let table: toml::Table = source
        .parse()
        .unwrap_or_else(|e| panic!("themes/{id}.toml is not readable TOML: {e}"));

    let name = table.get("name").and_then(|v| v.as_str());
    assert!(
        name.is_some_and(|n| !n.trim().is_empty()),
        "themes/{id}.toml has no name",
    );

    for field in COLORS {
        let Some(value) = table.get(*field) else {
            // Only `text` and `background` are required; the rest are derived
            // from the accent when they are absent, which is what most themes
            // want.
            assert!(
                *field != "text" && *field != "background",
                "themes/{id}.toml has no {field}",
            );
            continue;
        };
        let colour = value
            .as_str()
            .unwrap_or_else(|| panic!("themes/{id}.toml: {field} is not a string"));
        assert!(
            is_hex(colour),
            "themes/{id}.toml: {field} is {colour:?}, which the renderer cannot read — \
             colours are #abc, #abcd, #aabbcc or #aabbccdd and nothing else",
        );
    }

    table
        .get("order")
        .and_then(|v| v.as_integer())
        .unwrap_or_else(|| {
            panic!("themes/{id}.toml has no `order`, so nothing knows where to list it")
        })
}

/// The same alphabet and the same four lengths `parseColor` accepts.
fn is_hex(colour: &str) -> bool {
    let Some(digits) = colour.strip_prefix('#') else {
        return false;
    };
    matches!(digits.len(), 3 | 4 | 6 | 8) && digits.bytes().all(|b| b.is_ascii_hexdigit())
}
